---
title: "NOGA_stranding_map"
author: "Tori Burt"
date: "2024-11-26"
output: html_document
---

```{r load packages}

library(ggplot2)
library(maps)
library(ggforce)
library(RColorBrewer)
library(viridis)
library(marmap)
library(tidyverse)
library(scales)
library(dplyr)
library(tidyr)
library(stringr)
library(scales)
library(legendMap)
library(ggpubr)
library(sf)
library(ggforce)
library(scales)
library(patchwork)
library(ggeffects)
library(sp)
library(patchwork)
library(legendMap)
library(rlang)
library(devtools)
library(usethis)
library(ggspatial)
library(cowplot)
library(rgdal)

```

```{r load data}

#NOGA stranding data - ECCC and CSM interpreters
HL_eccc <- read.csv("data/Gannet_Summary_HL_2024_11_26.csv")

#load colony data
colonies <- read.csv("data/lesp_noga_colonies_large.csv")

#load Hurricane Larry windswath
larry_wind <- readOGR("data/Hurricane_Larry_Shapefiles/AL122021_windswath.shp") #radii for 34 KT, 50 KT, and 64 KT ref: https://ftp.nhc.noaa.gov/atcf/README
larry_wind <- fortify(larry_wind)

#load Hurricane Larry best track
larry_track <- readOGR("data/Hurricane_Larry_Shapefiles/AL122021_lin.shp")
larry_track <- fortify(larry_track)

#load world map data
world_map <- map_data("world")

```

```{r clean up data}

#filter for only NOGA colonies
noga_colonies <- colonies %>%
  filter(Species == "NOGA")

#filter for only NOGA and select relevant columns
HL_noga_eccc <- HL_eccc %>%
  filter(Species == "NOGA", Location != "Cape Race") %>% #Remove Cape Race obv. because it                                                               wasn't made by ECCC
  select(Date, Location, Lat, Lon, Num, Age, Live_dead)

#make columns that just contain year, month, and day of year
HL_noga_eccc$Date <- as.Date(HL_noga_eccc$Date)
HL_noga_eccc$Date <- as.POSIXlt(HL_noga_eccc$Date, format = "%m/%d/%Y")
HL_noga_eccc$Year <- HL_noga_eccc$Date$year
HL_noga_eccc$Month <- HL_noga_eccc$Date$mon + 1
HL_noga_eccc$Date <- as.POSIXct(HL_noga_eccc$Date)
HL_noga_eccc$yDate <- yday(HL_noga_eccc$Date)

#create database with sum of birds per location
Lat <- aggregate(Lat~Location,HL_noga_eccc, max)
names(Lat)[2] <- 'Lat'
Lon <- aggregate(Lon~Location,HL_noga_eccc, max)
names(Lon)[2] <- 'Lon'
totalnum <- aggregate(Num~Location,HL_noga_eccc,sum)
names(totalnum)[2] <- 'totalnum'
df <- merge(totalnum, Lon, by = "Location", all.x = TRUE)
HL_noga_eccc_max <- merge(df, Lat, by = "Location", all.x = TRUE)

#classifying variable
HL_noga_eccc_max$totalnum <- as.numeric(HL_noga_eccc_max$totalnum)

#specifying wind swath area
larry_piece <- larry_wind %>%
  filter(id != 2, id != 1, id != 3) %>%
  mutate(Wind_radii = c( "34-50 Knots", "> 50 Knots")[(id %in% c("4") & 
  as.numeric(as.character(piece)) == 1)+1] )

#subsetting data for Canada and NL
Canada <- subset(world_map, world_map$region =="Canada")
Newfoundland <- subset(world_map, world_map$subregion =="Newfoundland")
Fogo <- subset(world_map, world_map$subregion == "Fogo Island")

```

```{r counts of stranding and mortality}

#Total live-stranded and carcasses NOGA
sum(HL_noga_eccc$Num) #366 birds total

#Total max live-stranded adult NOGA
HL_noga_eccc_ad_live <- HL_noga_eccc %>%
  filter(Age != "SubAdult", Live_dead != "Dead")

sum(HL_noga_eccc_ad_live$Num) #169 adult birds alive

#Total carcass count adult NOGA
HL_noga_eccc_ad_dead <- HL_noga_eccc %>%
  filter(Age != "SubAdult", Live_dead != "Live")

sum(HL_noga_eccc_ad_dead$Num) #101 adult birds dead

#Total live-stranded juvenile NOGA
HL_noga_eccc_juv_live <- HL_noga_eccc %>%
  filter(Age != "Adult", Live_dead != "Dead")

sum(HL_noga_eccc_juv_live$Num) #67 juvenile birds alive

#Total carcass count juvnile NOGA
HL_noga_eccc_juv_dead <- HL_noga_eccc %>%
  filter(Age != "Adult", Live_dead != "Live")

sum(HL_noga_eccc_juv_dead$Num) #29 juvenile birds dead

```

```{r figure 4}

#NOGA map
NOGAmap <- ggplot()+ 
  coord_map(xlim = c(-54.7, -53.3), ylim = c(46.5, 47.5)) +
  xlab("") +
  ylab("") +
  geom_polygon(data = Newfoundland, aes(x = long, y = lat, group = group), colour = "black", fill = "light grey") +
  geom_polygon(data = larry_piece, aes(x = long, y = lat, group = group, fill = Wind_radii), alpha = 0.2, colour = "black", linewidth = 0.75) +
  geom_point(data = HL_noga_eccc_max, aes(size = totalnum, x = Lon, y = Lat), alpha = 0.5, colour = "black", fill = "grey") +
  theme(legend.text = element_text(size = 10), legend.key = element_rect(fill ="white"), legend.title = element_text(size = 12), text = element_text(size = 14)) +
  geom_point(data = noga_colonies %>% filter(Location == "Newfoundland"),  aes(x = Lon, y = Lat, pch = " "), size = 3, alpha = 0.7, colour = "black") +
  geom_path(data = larry_track, aes(x = long, y = lat, colour = " ", group = id), alpha = 1, linewidth = 2) +
  scale_color_manual(name = "Hurricane Larry track", values = c(" " = "#190E19FF")) +
  scale_shape_manual("Northern Gannet colony", labels = c(" "), values = c(15)) +
  labs(size = "Northern Gannet stranding or death") +
  scale_fill_discrete(labels = c('63-93', '> 93'), type = c('#7ED7AFFF','#414388FF')) +
  labs(fill = "Wind gusts (km/hr)") +
  xlab("Longitude") +
  ylab("Latitude") +
  theme(panel.background = element_rect(fill = 'white', colour = 'black', size = 1)) +
  scale_bar(lon = -54, lat = 46.48, distance_lon = 25, distance_lat = 6, distance_legend = 8, dist_unit = "km", orientation = F) +
   annotation_north_arrow(location = "tr", which_north = "true",
  pad_x = unit(-0.1, "in"), pad_y = unit(0.2, "in"), height = unit(1.5, "in"), width = unit(1.5, "in"), style =
  ggspatial::north_arrow_nautical(
      fill = c("grey40", "white"),
      line_col = "grey20"))

#bin stranding events
NOGAmap_bin <- NOGAmap + 
  scale_size_binned(breaks=c(1, 25, 50, 75, 100, 125,150),
                    labels=c("1", "25", "50","75","100","125", "150"),
                    limits = c(1, 150))

#Canada sub plot
CAmap <- ggplot() +
  coord_map(xlim = c(-60, -51), ylim = c(46, 52)) +
  xlab("") +
  ylab("") +
  geom_polygon(data = Newfoundland, aes(x = long, y = lat, group = group), colour = "black", fill = "light grey") +
  geom_polygon(data = Fogo, aes(x = long, y = lat, group = group), colour = "black", fill = "light grey") +
  geom_polygon(data = larry_piece, aes(x = long, y = lat, group = group, fill = Wind_radii), alpha = 0.3, colour = "black", linewidth = 0.75) +
  scale_fill_discrete(labels = c('63-93', '> 93'), type = c('#7ED7AFFF','#414388FF')) +
  geom_path(data = larry_track, aes(x = long, y = lat, group = "id"), colour = "black", alpha = 1, linewidth = 2) +
  geom_rect(aes(xmin = -54.7, xmax = -53.3, ymin = 46.5, ymax = 47.5), alpha = 0, colour = "black") +
  theme_void() +
  theme(panel.border = element_rect(fill = NA, colour = "black"), plot.background = element_rect(fill = "white")) +
  theme(legend.position = "none")

#create inset map
nogastrand <- ggdraw() +
  draw_plot(NOGAmap_bin) +
  draw_plot(CAmap,
    height = 0.34, width = 0.17,
    x = 0.1955,
    y = 0.651)

#save figure
ggsave(nogastrand, filename = "figures/NOGA_stranding.jpeg", width = 14.5, height = 7.5, dpi = 175)

```